export interface AnimalMetricColumn {
  key: string
  label: string
  numeric?: boolean
}

export const ANIMAL_METRIC_COLUMNS: AnimalMetricColumn[] = [
  { key: 'hhp_dollar', label: 'HHP$', numeric: true },
  { key: 'tpi', label: 'TPI', numeric: true },
  { key: 'nm_dollar', label: 'NM$', numeric: true },
  { key: 'cm_dollar', label: 'CM$', numeric: true },
  { key: 'fm_dollar', label: 'FM$', numeric: true },
  { key: 'gm_dollar', label: 'GM$', numeric: true },
  { key: 'f_sav', label: 'F SAV', numeric: true },
  { key: 'ptam', label: 'PTAM', numeric: true },
  { key: 'cfp', label: 'CFP', numeric: true },
  { key: 'ptaf', label: 'PTAF', numeric: true },
  { key: 'ptaf_pct', label: 'PTAF%', numeric: true },
  { key: 'ptap', label: 'PTAP', numeric: true },
  { key: 'ptap_pct', label: 'PTAP%', numeric: true },
  { key: 'pl', label: 'PL', numeric: true },
  { key: 'dpr', label: 'DPR', numeric: true },
  { key: 'liv', label: 'LIV', numeric: true },
  { key: 'scs', label: 'SCS', numeric: true },
  { key: 'mast', label: 'MAST', numeric: true },
  { key: 'met', label: 'MET', numeric: true },
  { key: 'rp', label: 'RP', numeric: true },
  { key: 'da', label: 'DA', numeric: true },
  { key: 'ket', label: 'KET', numeric: true },
  { key: 'mf', label: 'MF', numeric: true },
  { key: 'ptat', label: 'PTAT', numeric: true },
  { key: 'udc', label: 'UDC', numeric: true },
  { key: 'flc', label: 'FLC', numeric: true },
  { key: 'sce', label: 'SCE', numeric: true },
  { key: 'dce', label: 'DCE', numeric: true },
  { key: 'ssb', label: 'SSB', numeric: true },
  { key: 'dsb', label: 'DSB', numeric: true },
  { key: 'h_liv', label: 'H LIV', numeric: true },
  { key: 'ccr', label: 'CCR', numeric: true },
  { key: 'hcr', label: 'HCR', numeric: true },
  { key: 'fi', label: 'FI', numeric: true },
  { key: 'gl', label: 'GL', numeric: true },
  { key: 'efc', label: 'EFC', numeric: true },
  { key: 'bwc', label: 'BWC', numeric: true },
  { key: 'sta', label: 'STA', numeric: true },
  { key: 'str', label: 'STR', numeric: true },
  { key: 'dfm', label: 'DFM', numeric: true },
  { key: 'rua', label: 'RUA', numeric: true },
  { key: 'rls', label: 'RLS', numeric: true },
  { key: 'rtp', label: 'RTP', numeric: true },
  { key: 'ftl', label: 'FTL', numeric: true },
  { key: 'rw', label: 'RW', numeric: true },
  { key: 'rlr', label: 'RLR', numeric: true },
  { key: 'fta', label: 'FTA', numeric: true },
  { key: 'fls', label: 'FLS', numeric: true },
  { key: 'fua', label: 'FUA', numeric: true },
  { key: 'ruh', label: 'RUH', numeric: true },
  { key: 'ruw', label: 'RUW', numeric: true },
  { key: 'ucl', label: 'UCL', numeric: true },
  { key: 'udp', label: 'UDP', numeric: true },
  { key: 'ftp', label: 'FTP', numeric: true },
  { key: 'rfi', label: 'RFI', numeric: true },
  { key: 'beta_casein', label: 'Beta-Casein' },
  { key: 'kappa_casein', label: 'Kappa-Casein' },
  { key: 'gfi', label: 'GFI', numeric: true },
]
